# Generated by Django 4.2.5 on 2023-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='number',
            field=models.IntegerField(),
        ),
    ]
