# Generated by Django 4.2.4 on 2023-09-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0004_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
