# Generated by Django 4.2.4 on 2023-09-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0005_alter_trainer_age_alter_trainer_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymadmin',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
