# Generated by Django 4.2.4 on 2023-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0006_gymadmin_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='gymTrainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
