# Generated by Django 4.2.4 on 2023-09-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0007_gymtrainers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gymTrainers',
        ),
    ]
