# Generated by Django 4.2.4 on 2023-09-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0008_delete_gymtrainers'),
    ]

    operations = [
        migrations.CreateModel(
            name='gymPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('duration', models.TextField()),
            ],
        ),
    ]
