# Generated by Django 4.2.4 on 2023-09-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0009_gymplans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymplans',
            options={'verbose_name_plural': 'gym Plans'},
        ),
        migrations.AddField(
            model_name='gym',
            name='subscription',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='gymApp.gymplans'),
        ),
    ]
