# Generated by Django 4.2.4 on 2023-09-18 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0013_remove_bookslots_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslots',
            name='plans',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='gymApp.gymplans'),
        ),
    ]
